- README.md
- client.go
- client_test.go
- client_util.go
- cmd/goclient/goclient.go
- faucet.go
- http.go
- nodeClient.go
reorg client setup
improve HttpError
goclient fixes
nodeClient sends x-aptos-client: header
> reorg client setup, &c

- client.go
- nodeClient.go
- nodeInfo.go
- nodeInfo_test.go
- resource.go
- util.go
- util_test.go
add NodeInfo convenience accossors to parse long int in string
add options to APTTransferTransaction
misc cleanup
> API usability enhancements

- account.go
- account_test.go
- client.go
- client_test.go
- fungible_asset_client.go
- fungible_asset_client_test.go
- nodeClient.go
- util.go
- util_test.go
Refactors transaction submission.  Now, it's super easy to reuse, submit transactions etc.  Take a look at the fungible asset client for the first example of this.
This also fixes the object derivation that was broken
> [txn] Refactor transaction submission, add fungible asset client

- client.go
- fungible_asset_client.go
- fungible_asset_client_test.go
- nodeClient.go
Adds view function support, and a full suite of fungible asset support.
> [client] Add view functions

- account.go
- accountInfo.go
- accountResourceRecord.go
- account_test.go
- authenticator.go
- bcs.go
- bcs_test.go
- client.go
- client_test.go
- cmd/goclient/goclient.go
- crypto.go
- ed25519.go
- fungible_asset_client.go
- fungible_asset_client_test.go
- nodeClient.go
- resource.go
- scripts/cover.sh
- transactions.go
- transactions_test.go
- typetag.go
- typetag_test.go
- util.go
- util_test.go
- Fixes some account consistency
- Changes signing to come from account rather than private key
- Enables non-private key signers
- Fix uleb128 to only take the supported uint32
- Lots of documentation
- Private Key / Public Key loading from hex string / writing to hex string
> [cleanup] Various cleanups

- .github/actions/run-go-tests/action.yaml
- .github/workflows/run-go-tests.yaml
- bcs.go
- examples/performance_transaction/main.go
- nodeClient.go
add `go fmt` checking and example running to Go test action
add `BcsSerialize()` convenience function
> testing and tweaks

- bcs/bcs.go
- core/resource.go
- nodeClient.go
- transactions.go
- typetag.go
fix usage of generic functions
> fix usage of SerializeSequence

- CHANGELOG.md
- account.go
- client.go
- crypto/authenticator.go
- crypto/crypto.go
- crypto/ed25519.go
- nodeClient.go
- signedTransaction.go
- Add block APIs
- Add private key imports, and authentication key
- Add signed transaction hashes
> Add more functionality

- fungible_asset_client.go
Fix misspelling on the object type
> [fa-client] Fix fungible client on transfer

- go.mod
- go.sum
Updates the go/crypto library
CI
> [deps] Update go/crypto

- CHANGELOG.md
- README.md
- api/events.go
- api/module.go
- api/payloads.go
- api/signature.go
- api/transactions.go
- api/util.go
- bcs/bcs.go
- bcs/deserializer.go
- bcs/serializer.go
- client.go
- client_test.go
- code.go
- crypto/authenticationKey.go
- crypto/authenticator.go
- crypto/crypto.go
- crypto/ed25519.go
- crypto/multiEd25519.go
- crypto/multiKey.go
- crypto/secp256k1.go
- crypto/singleKey.go
- multisig.go
- nodeClient.go
Added a ton of examples in the docs inline, which should help readability on the autogenerated go docs
> Docs updates

- CHANGELOG.md
- concClient.go
- concClient_test.go
- nodeClient.go
This adds a concurrent client for goroutines.  Future implementations will likely merge it with the client directly.
Added tests around some of the common tasks
> [concurrent] Add a concurrent client wrapper around the client

- CHANGELOG.md
> [release] 0.4.0 changelog update

- api/blocks.go
- api/events.go
- examples/alternative_signing/main.go
- examples/external_signing/main.go
- examples/fungible_asset/main.go
- examples/onchain_multisig/main.go
- examples/performance_transaction/main.go
- examples/transfer_coin/main.go
Cleans up examples to use devnet instead of local, and no internal packages
> [examples] Change examples to use devnet, not use internal packages

- CHANGELOG.md
> [release] v0.4.1

- api/payloads.go
- api/signature.go
- api/transactions.go
- api/writeSet.go
- client.go
- examples/sponsored_transaction/.gitignore
- examples/sponsored_transaction/main.go
- internal/types/account.go
- nodeClient.go
- rawTransaction.go
As requested, there needed to be an example around sponsored transactions
The example works perfectly, and the JSON API lenient change allows tests to pass against the newest CLI
> [fee payer] Fix fee payer, and make JSON API lenient to enum changes

- CHANGELOG.md
> [release] Release v0.5.0

- CHANGELOG.md
- api/writeSet.go
- api/writeSet_test.go
Fixes https://github.com/aptos-labs/aptos-go-sdk/issues/63
> [write-set] Fix delete resource write set

- crypto/ed25519.go
- crypto/multiEd25519.go
- crypto/multiKey.go
- crypto/secp256k1.go
- crypto/singleKey.go
- transactionSubmission.go
Taking additional suggestion from and closes https://github.com/aptos-labs/aptos-go-sdk/issues/65
> [refactor] Cleanup switch statements

- .github/actions/run-go-tests/action.yaml
- CHANGELOG.md
- README.md
- api/payloads.go
- api/signature_test.go
- api/transactions.go
- api/transactions_test.go
- api/writeSet_test.go
- client_test.go
- crypto/ed25519.go
- crypto/multiEd25519.go
- crypto/secp256k1.go
- examples/external_signing/main.go
- examples/performance_transaction/main.go
- examples/sending_concurrent_transactions/main.go
- transactions_test.go
This adds significant coverage testing, and a couple fixes that will go out in a patch release.
> Additional test coverage and some fixes

- CHANGELOG.md
- api/blocks.go
- nodeClient.go
Fixes two bugs brought up from others
> Block bug fixes

- api/payloads_test.go
- api/signature_test.go
- bcs/deserializer.go
- bcs/serializer.go
- crypto/ed25519.go
- crypto/ed25519_test.go
> Various cleanups to add test coverage

- CHANGELOG.md
Update changelog for release to 0.7.0
> [release] Setup release for 0.7.0

- CHANGELOG.md
- client.go
- client_test.go
- nodeClient.go
Before certain size pages would not work concurrently, now it will properly handle a large limit without a given start value.
Resolves https://github.com/aptos-labs/aptos-go-sdk/issues/86
See E2E tests
https://github.com/aptos-labs/aptos-go-sdk/issues/86
> [client] Add support for Account transactions, and any size page

- examples/transfer_coin/main.go
- indexerClient.go
- nodeClient.go
> Various cleanups

- CHANGELOG.md
Updates changelog for the latest release
> [release] v1.0.0

- CHANGELOG.md
> [release] v1.1.0

- CHANGELOG.md
Releases 1.2.0 fixing some implementation differences for Multikey and adding option support for BCS
See CI
> [release] Version 1.2.0

- CHANGELOG.md
- client.go
- fungible_asset_client.go
- nodeClient.go
Adds ability for predetermined queries to use version as well.
> [view] Allow querying APT balance and FA properties by version

- CHANGELOG.md
Release v1.3.0 today, updates changelog
> [release] Release v1.3.0

- CHANGELOG.md
> [release] Update changelog for v1.4.0 release

- client.go
> fix misspelling in doc

- examples/offchain_multisig/.gitignore
- examples/offchain_multisig/main.go
- examples/offchain_multisig/main_test.go
Adds a full example for Multikey.  Will add simulation to the main SDK and update the example accordingly in a future PR.
> [examples] Add off-chain multisig

- CHANGELOG.md
> [release] Release v1.5.0

- CHANGELOG.md
- client.go
- client_test.go
- crypto/authenticator.go
- crypto/simulation.go
- examples/multi_agent/.gitignore
- examples/multi_agent/main.go
- examples/sponsored_transaction/main.go
- nodeClient.go
Add the ability to simulate any transactions
Resolves https://github.com/aptos-labs/aptos-go-sdk/issues/93
> Add simulate anything

- examples/script_args_transaction/main.go
> [example] Script arg example

- .github/actions/run-go-tests/action.yaml
- .github/actions/run-gofumpt/action.yaml
- .github/workflows/gofumpt-lint.yaml
- README.md
> [ci] Add gofumpt formatting check

- CHANGELOG.md
- client.go
- client_test.go
- indexerClient.go
- nodeClient.go
- view.go
Fixes interfaces to actually match across types
> [interfaces] Fix client interfaces to be consistent and enforced

- CHANGELOG.md
> [release] v1.6.1

- CHANGELOG.md
Fixes some bugs in the fungible asset client
> [release] Release 1.6.2

- client_test.go
- internal/testutil/test_helpers.go
> [test] Fix faucet failure due to 0 funding

- CHANGELOG.md
> [release] Release 1.7.0

- client.go
Follow up to https://github.com/aptos-labs/aptos-go-sdk/pull/167
> Adding EventsByCreationNumber to the client interface

- CHANGELOG.md
- typeConversion.go
- typeConversion_test.go
Fixes nested type conversion, removes a lot of excess code associated
Tests nested types, with options, and other examples
> [typeTag] fix automatic type conversion for nested vectors

- CHANGELOG.md
- client.go
- nodeClient.go
- typeConversion.go
- typeConversion_test.go
Releases v1.9.0 which fixes issues in argument auto-conversion.
> [release] v1.9.0

- CHANGELOG.md
> [release] Release v1.10.0
