aptos-labs/aptos-go-sdk

client.go

- Add TransactionByVersion
- Remove deprecated ioutil.ReadAll
- explicitly drop errors that are not needed

[client] Add TransactionByVersion and cleanup some warnings

---

accountInfo.go
accountResourceInfo.go
accountResourceRecord.go
client.go
client_test.go
cmd/goclient/goclient.go
faucet.go
http.go
nodeClient.go
nodeInfo.go
util.go

- Adds basic network configurations for known networks
- Adds a full e2e test of transaction submission and checking
- Merges RestClient and Faucet client like the TS SDK

[client] Add some basic testing and Network

---

account.go
cmd/goclient/goclient.go
crypto.go
ed25519.go
transactions.go
transactions_test.go
util.go

Pulls ed25519 into separate files, makes signing generic

[crypto] Refactor crypto to be generic / pull ed25519 out of transaction logic

---

client.go
faucet.go
nodeClient.go

- add a `NewFaucetClient` constructor, allowing creation of `FaucetClient` independent of `Client`
- use `*url.URL` and `JoinPath`
- move `truthy` into `nodeClient.go` where it is used

Update faucet client

---

bcs/bcs_test.go
bcs/deserializer.go
bcs/serializer.go
cmd/goclient/goclient.go
nodeClient_test.go
typetag.go
typetag_test.go

High coverage now on BCS and TypeTag core parts of the code.  This includes:
1. Fixing a bug with bool in deserialization
2. Adding errors for when deserialization but you run off the end of the buffer
3. Adding TypeTag support for signer, U128, U256, Vector, and removed extra data
4. Lots more testing!

[bcs / type tag] Fix some bugs, add error handling, full testing

---

CHANGELOG.md
client_test.go
client_util.go
script.go
transactionPayload.go
util.go
util_test.go

Added testing for Scripts, and some util functions.  Built on top of https://github.com/aptos-labs/aptos-go-sdk/pull/28

[transactionPayload] Support scripts

---

nodeClient.go

`SubmitTransaction` fails on some of our tests with:
```{"error": "HttpError POST \"http://172.254.0.101:8080/v1/transactions\" -> \"411 Length Required\" \"{\\\"message\\\":\\\"missing `Content-Length` header\\\",\\\"error_code\\\":\\\"web_framework_error\\\",\\\"vm_error_code\\\":null}\""}```
from [NewRequest](https://pkg.go.dev/net/http#NewRequestWithContext) docs:
> If body is of type [*bytes.Buffer](https://pkg.go.dev/bytes#Buffer), [*bytes.Reader](https://pkg.go.dev/bytes#Reader), or [*strings.Reader](https://pkg.go.dev/strings#Reader), the returned request's ContentLength is set to its exact value (instead of -1), GetBody is populated (so 307 and 308 redirects can replay the body), and Body is set to [NoBody](https://pkg.go.dev/net/http#NoBody) if the ContentLength is 0.
from the …

nodeClient.go: assign body at NewRequest

---

CHANGELOG.md
account.go
crypto/authenticator.go
crypto/authenticator_test.go
crypto/crypto.go
crypto/ed25519.go
crypto/ed25519_test.go
signedTransaction.go

The ed25519 library refers to the "private key" as the private and public key together.  The private key alone is referred to as the "seed".  So, this fixes it accordingly.
Additionally, fixes some consistency issues for authentication keys

[ed25519] Fix number of bytes in ed25519 signature

---

api/module.go
api/module_test.go
api/writeSet.go

There was a bug in parsing the bytecode field from Aptos API responses (error: `illegal base64 data at input byte ...`. This was tracked down to the attempt to unmarshal `bytecode` which is a JSON hex string into a byte array. This should use the existing HexBytes type instead.
Also changed WriteSetChangeWriteModule.StateKeyHash to `Hash` type to be consistent with the other `WriteSet` types
Added some basic tests to validate unmarshaling works as intended.
Running the `TestModule_MoveBytecode` test with the old implementation (`Bytecode []byte`) throws an error: `illegal base64 data at input byte 40`.

Fix bytecode JSON unmarshalling

---

crypto/secp256k1.go

There are incorrect usage of `secp256k1` methods instead of the go-ethereum crypto package (`ethCrypto`) methods in the implementation of `Secp256k1PrivateKey` and `Secp256k1PublicKey` within the Aptos Go SDK here: 
https://github.com/aptos-labs/aptos-go-sdk/blob/main/crypto/secp256k1.go
File: https://github.com/aptos-labs/aptos-go-sdk/blob/main/crypto/secp256k1.go
**Current code**: 
```go
func (key *Secp256k1PrivateKey) SignMessage(msg []byte) (sig Signature, err error) {
hash := util.Sha3256Hash([][]byte{msg})
// TODO: The eth library doesn't protect against malleability issues, so we need to handle those
signature, err := secp256k1.Sign(hash, key.Bytes())
if err != nil {
return nil, err
}
// Strip the recovery bit
return &Secp256k1Signature{
signature[0:64],
}, nil
}
```
- **Issue**: …

Incorrect Use of secp256k1 Methods

---

crypto/secp256k1.go
crypto/secp256k1_test.go

Finally sat down and realized the Go SDK wasn't hashing the payloads, which is why verification wasn't working before.

[secp256k1] Fix verification

---

client.go
client_test.go
nodeClient.go
transactionSubmission.go

use different client for submission and N different clients for txn status waiting close channels when they're done
simplify channel consuming syntax
WaitGroup-s for intra-function goroutines
cleaner/stricter goroutine/chan usage
This is a test

rearrange concurrency in Test_Concurrent_Submission

---

bcs/deserializer.go
bcs/serializer.go
client_test.go
crypto/cryptoMaterial_test.go
crypto/ed25519.go
crypto/multiEd25519_test.go
crypto/multiKey_test.go
crypto/secp256k1_test.go
examples/alternative_signing/main_test.go
examples/external_signing/main_test.go
examples/fungible_asset/main_test.go
examples/onchain_multisig/main_test.go
examples/performance_transaction/main_test.go
examples/sponsored_transaction/main_test.go
examples/transfer_coin/main_test.go
transactionSubmission.go

Cleans up tests, adds some more coverage, fixes concurrent id passing

[tests] Cleanup testsuite

---

CHANGELOG.md
api/events.go
api/events_test.go
api/util.go

There are two formats, one for resources, and one for events.  I wrongly formatted the resource format to parse the event format.  This fixes it.  Thanks @jmmcatee for pointing it out!
Fixed the event tests accordingly to match the other copied test inputs.
Closes https://github.com/aptos-labs/aptos-go-sdk/issues/75

[events] Fix event GUID parsing

---

CHANGELOG.md
crypto/ed25519.go
go.mod
go.sum

Ed25519 consensus uses ZIP215 to ensure that the signatures are verified in the same way.
Closes: https://github.com/aptos-labs/aptos-go-sdk/issues/14

[ed25519] Use ed25519 consensus for verification of signatures

---

CHANGELOG.md
crypto/authenticator.go
crypto/multiKey.go
crypto/multiKey_test.go
signer_test.go

Multikey signatures before didn't allow for gaps in the signatures, and required always to have the keys in order.  This fixes it accordingly.  It now matches the Rust implementation.
See tests which now test gaps, mixed signatures, and different orders.

[multikey] Fix verification and building of multikey signatures

---

client.go

In my testing, I was unable to easily set the http client configuration without a lot of manual code.  This gets rid of it, and leaves room for future expansion of configuration of a client.
Additionally, per https://github.com/aptos-labs/aptos-go-sdk/issues/94 it adds an interface for each of the clients, for mocking purposes.
Resolves https://github.com/aptos-labs/aptos-go-sdk/issues/94

[client] Add more client options

---

CHANGELOG.md
fungible_asset_client.go

Adds remaining view functions except (is balance at least and is_store_dispatchable)
Both of those, probably are only useful within a move context, assets should be known they're dispatchable at the asset level, not store level.
Also, refactored a bit to remove TODOs and reduce duplication

[fa] Add icon_uri and project_uri to client

---

CHANGELOG.md
README.md
bcs/bcs_test.go
bcs/deserializer.go
bcs/serializer.go

Adds optional helper function for serializing values e.g. Option<String>
Added unit test for uint8, the rest are comparable since it does not add pre-created functions.

[bcs] Add optional bcs serialization

---

CHANGELOG.md
client_test.go
crypto/multiKey.go
crypto/multiKey_test.go
signer_test.go

There was a slight difference in implementation, where the bitmap was not being variable length, though it was meant to be variable length.
This fixes it and adds a python generated output as a comparison.
Adds a test for compatibility, along with existing submission tests in examples

[multikey] Fix multikey serialization

---

CHANGELOG.md
api/events.go
api/events_test.go

Moves non-compliant data structures to `__any_data__` for events
See tests

[events] Allow for events to be non structs

---

client_util.go

There's an ordering issue here in the assumptions of which values are available or not.  I've never come upon this issue, but it's probably based on the build system.
Resolves https://github.com/aptos-labs/aptos-go-sdk/issues/114

[init] Fix initializaiton bug for setting params based off of build info

---

client.go
nodeClient.go

The `AptosRpcClient` interface is supposed to be implemented by `NodeClient`:
> // AptosRpcClient is an interface for all functionality on the Client that is Node RPC related.  Its main implementation
// is [NodeClient]
But doesn't actually satisfy the interface due to two methods:
1. NodeAPIHealthCheck
```
methods are missing: NodeAPIHealthCheck(durationSecs ...uint64) (api. HealthCheckResponse, error)
```
I wasn't sure if you'd want to break compatibility by renaming the method and added a new method `NodeAPIHealthCheck` and kept the old one `NodeHealthCheck` while marking it as deprecated.
2. BuildSignAndSubmitTransaction
```
need the method: BuildSignAndSubmitTransaction(sender *Account, payload TransactionPayload, options ...any) (data *api. SubmitTransactionResponse, err error)
have …
```

Make NodeClient satisfy AptosRpcClient interface

---

client.go
nodeClient.go
nodeClient_test.go

Added `EventsByHandle` to the client interface.
```go test ./...```

Add EventsByHandle to the nodeClient 

---

internal/types/account.go
typetag.go
typetag_test.go

Similar to the TypeScript SDK, this ports over the logic that handles all of the different types into structured types.
Resolves https://github.com/aptos-labs/aptos-go-sdk/issues/76
There's a decent test to test out multiple different cases

[TypeTag] Add parsing for strings to TypeTag

---

CHANGELOG.md
account.go
internal/types/account.go
internal/types/accountAddress_test.go
internal/types/account_test.go
internal/util/util.go

1. Change authkey input to accounts to address
2. Allow for extracting private key from accounts
Added 100% possible coverage on types/ folder

[account] Improve account experience

---

integration_test/transactionSubmission/multi_sender_test.go
integration_test/transactionSubmission/single_sender_test.go
internal/testutil/test_helpers.go
transactionSubmission.go

PR addresses the TODO comment in `BuildSignAndSubmitTransactionsWithSignFunction` regarding configurable buffer sizes. 
- This provides more predictable resource control and memory usage.
- Ran integration tests against Devnet
1. **Integration Tests**
- Added two comprehensive integration tests in `integration_test/transactionSubmission/`
- `TestBuildSignAndSubmitTransactionsWithSignFnAndWorkerPoolWithOneSender`
- Tests single sender submitting multiple transactions
- `TestBuildSignAndSubmitTransactionsWithSignFnAndWorkerPoolWithMultipleSenders`
- Tests multiple concurrent senders

Add Configurable Worker Pool for Transaction Processing

---

nodeClient.go

- Optimize WaitForTransaction.
Adopt the WaitForTransaction polling method implemented via [wait_by_hash api](https://aptos.dev/en/build/apis/fullnode-rest-api-reference#tag/transactions/GET/transactions/wait_by_hash/{txn_hash}) in the Typescript SDK.
However, there is a concern that this might conflict with the PR using Golang context for HTTP requests. 
In that case, a ctx should be accepted and used for polling.
- Verify that WaitTransactionByHash operates correctly.
- Confirm that PollForTransaction produces the same results as before.
-  https://aptos.dev/en/build/apis/fullnode-rest-api-reference#tag/transactions/GET/transactions/wait_by_hash/{txn_hash}
-  https://github.com/aptos-labs/aptos-go-sdk/pull/128

Optimize WaitForTransaction

---

CHANGELOG.md

Releases 1.6.0
Changelog:
- [`Feature`] Add the ability for ABI simple type conversion of entry function arguments with both remote and local ABI
- Add ability to simulate for any transaction including multi-agent and fee payer
- [`Fix`] Ensure proper cleanup of response body on read error to prevent potential memory leak.
- [`Fix`] Fixes possible conflicts between signatures of multiple goroutines
- [`Breaking`] Change ExpirationSeconds from int64 to uint64
- [`Fix`] Fix a self calling function in the client
- [`Fix`/`Breaking`] Fix fungible asset API calls that didn't return a value
- [`Fix`] Fix errors from failed transactions in concurrent submission
- [`Fix`] Fix AptosRpcClient, AptosFaucetClient, AptosIndexerClient interfaces to be enforced on concrete types properly
- [`Fix`] A few …

[release] Bump to 1.6.0

---

CHANGELOG.md
transactionSubmission.go

- The use of atomic operations is unnecessary in this context.
- Since all return paths ensure the channel is closed, the closure can be simply defered.

Refactor: Simplify building transactions

---

internal/types/accountAddress.go

related to issue: https://github.com/aptos-labs/aptos-go-sdk/issues/157
`AccountAdddress` -> `AccountAddress`

Fix typo in error message: AccountAdddress

---

.gitignore
CHANGELOG.md
crypto/ed25519.go
crypto/ed25519_test.go
crypto/secp256k1.go
crypto/secp256k1_test.go

Add default string export to use the AIP-80 format.
https://github.com/aptos-labs/aptos-go-sdk/pull/107

[aip80] Default the string format for private keys to be AIP-80
